version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: achraf
      MYSQL_DATABASE: apms
    ports:
      - "3306:3306"  # Map host port 3306 to container port 3306
    networks:
      - apms_network

  apms:
    image: apms  # Replace with your apms image name
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/apms
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: achraf
    depends_on:
      - mysql
    networks:
      - apms_network

networks:
  apms_network:
    driver: bridge
