version: '3.8'
#196.84.127.164
services:
  apms:
    image: apms
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.0.150:3306/amps?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    ports:
      - "8080:8080"
    networks:
      - apms_network

networks:
  apms_network:
    driver: bridge